import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Template from "./template";
import HeaderMenu from "./components/header/HeaderMenu";
import LogoAnimation from "./components/animation/LogoAnimation";
import PageTransition from "./components/animation/PageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add PageTransition here */}
        <PageTransition />

        <Template>
          <LogoAnimation />
          <HeaderMenu />
          {children}
        </Template>
      </body>
    </html>
  );
}
